config/routes.rb
MentorMentee::Application.routes.draw do

 

  resources :answers
  resources :questions do 
 get 'load_subcategories',:on => :collection

end 

  namespace :admin do resources :subcategories end

  namespace :admin do resources :categories end

  namespace :admin do resources :mentors end

  namespace :admin do resources :mentees end

  namespace :admin do resources :home
	get "accounts"
  end

 	get "credentials/category"
	get "credentials/myprofile"
	get "credentials/studymat"
	get "credentials/career"
	get "credentials/contactus"
	get "credentials/question"
  devise_for :users, :path_names => { :sign_up => "register" } 

  
   devise_scope :user do 

get "myprofiles/edit"
get "myprofiles/update"
get "myprofiles/index"
  resources :credentials 
   resources :users
resources :myprofiles
  resources :login
  resources :questions
  resources :answers
   root :to => 'credentials#index'
end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
 validates :name, :presence => true 
 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
layout 'application'
prepend_before_filter :authenticate_user!

  # GET /questions
  # GET /questions.xml
  def index
     
    #  @questions = Question.all

    # respond_to do |format|
     # format.html # index.html.erb
     # format.xml  { render :xml => @questions }
    #end
  
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])
    @answerlist = Answer.where("question_id = ?", @question.id )
   
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new
     if request.xhr?
          
            @subcat = Subcategory.find(:all,:conditions=>['category_id=?',params[:id]])
            render :update do |page|
            page.replace_html :test, :partial => 'test'
          end
     else
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question] )
    @question.user_id=current_user.id
    @question.avatar_file_name =current_user.avatar_file_name
   respond_to do |format|
    if @question.save
         format.html { render :action => "create" }    
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end    
      end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end

def load_subcategories
puts "#### Category Id - #{params[:id]}"
@subcategories = Subcategory.where(:category_id => params[:id])
respond_to do |format|
format.js{
render :update do |page| 
page[:question_subcategory_id].replace collection_select(:question,:subcategory_id, @subcategories , :id, :name)
end
}
end
end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<html>
<head>


</head>
<body bgcolor ="silver">
<br /><br />
<%= form_for(@question) do |f| %>
<<<<<<< HEAD
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div><br />
<div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :description ,:rows => 5,:cols => 34 %>
  </div><br />
  <div class="field">
    <%= f.label :category_id %><br /> 
  
      <%= f.collection_select :category_id, Category.find(:all), :id, :name ,{:prompt=>'----select category---'},{ :onchange=>"#{remote_function(:url=>{:action=>'load_subcategories'},:with =>"'id='+value")}" }%>	

  </div><br />


  <div class="field">
    <%= f.label :subcategory_id %><br />
    <%= f.collection_select :subcategory_id, {},:id, :name,{},{:style=>'width:17.5%'} %><br /><br /> 

  </div><br />
  <div class="actions">
   
    <%= f.submit %>

  </div>
=======
<% if @question.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

<ul>
<% @question.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div><br />
<div class="field">
<%= f.label :Description %><br />
<%= f.text_area :description ,:rows => 5,:cols => 34%>
</div><br />
<div class="field">
<%= f.label :category_id %><br />

<%= f.collection_select :category_id, Category.find(:all), :id, :name ,{:prompt=> 'Select Category'},{ :onchange=>"#{remote_function(:url=>{:action=>'load_subcategories'} ,:with =>"'id='+value")}" }%>

</div><br />


<div class="field">
<%= f.label :subcategory_id %><br />
<%= f.collection_select :subcategory_id, Subcategory.find(:all), :id, :name %><br /><br />

</div><br />
<div class="actions">

<%= f.submit %>

</div>
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d
<% end %>
</body></html>

app/views/questions/_test.html.erb
  
<%= select("question", "subcategory_id", @subcat.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})%>

app/views/questions/create.html.erb
<center>
<table CLASS="formbg" >

<h2><p id="notice"><%= notice %></p></h2>
<table>
<tr>
<tr><td>
  <br/><b>Name:</b>
  <%= @question.name %></td></tr>

<tr><td>
  <b>Description:</b>
  <%= @question.description %></td></tr>

<tr><td><%= link_to 'Back', questions_path,:id => @question.id %> </td></tr>

</table ></center>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<<<<<<< HEAD
<html>

<body bgcolor = "silver">

<img src ="/images/discuss.jpg" width="100%" height="100px" align = "top"/>

<body >

<h1><blink><%= link_to 'Post A Question', new_question_path %><blink></h1><br /><br />
<% @ques = Question.find(:all, :order => 'created_at  DESC')%>

<% @ques.each do |questions| %>

  <h5><%=  link_to questions.name ,:controller => 'questions',:action => 'show' ,:id => questions.id%></h5>
   <% @count = Answer.where(:question_id => questions.id) %>   
<% @subcat = Subcategory.find(questions.subcategory_id)%>
 <h6> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; in 
 <%= link_to @subcat.name ,:controller => 'credentials',:action => 'question' ,:id => @subcat.id %> 
&nbsp; &nbsp; &nbsp; Answers(<%=  @count.count %>) &nbsp; &nbsp; &nbsp; Posted <%= time_ago_in_words(questions.created_at) %> ago</h6><br /><br />
=======
<br/><br/><br/><h1><blink><%= link_to 'Post A Question', new_question_path %><blink></h1><br/>

<h1><br/> Questions </h1>
<% @ques = Question.find(:all)%>

<% @ques.each do |questions| %>


 <h3><%=  link_to questions.name ,:controller => 'questions',:action => 'show' ,:id => questions.id%></h3>
   <% @count = Answer.where(:question_id => questions.id) %>   
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; in <%= link_to Category.find(questions.category_id).name unless questions.category_id.blank?%> &nbsp; &nbsp; &nbsp; Answers(<%=  @count.count %>)- <%= time_ago_in_words(questions.created_at) %> ago
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d

<%end%>
<%= yield%>
</h>
<br />

<<<<<<< HEAD
</body>
</html>
=======
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d

app/views/questions/new.html.erb
<<<<<<< HEAD
<br /><h1>Post Your Question</h1>
=======

<h1>Post Your Question</h1>
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d

<%= render 'form' %>
<%= link_to 'Back', questions_path  %> 

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
 

<p>
<<<<<<< HEAD
  <br />
<h2> <b>Question:</b> <%= @question.name %></h2>
<br /> <br />
<%= link_to "Answer This Question" ,:controller => 'answers',:action =>'new',:id => @question.id%><br /><br /><br /><br />
</p>
<% @answerlist.each do |answer| %>
  <tr>
     <td> <h5><%= answer.name%> </h5></td>   
     Posted <%= time_ago_in_words(answer.created_at) %> ago <br /><br />
=======
  
<h2> <b><br/><br/>Question:</b> <%= @question.name %></h2>
<br /> <br />
<%= link_to "Answer This Question" ,:controller => 'answers',:action =>'new',:id => @question.id%><br/><br/>
</p>
<% @answerlist.each do |answer| %>
  <tr>
     <td> <h5><%= answer.name%> </h5></td> 
     &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp;Posted <%= time_ago_in_words(answer.created_at) %>  ago <br/><br/>
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d
<% end%>