config/routes.rb
MentorMentee::Application.routes.draw do

 

  resources :answers
  resources :questions do 
 get 'load_subcategories',:on => :collection

end 

  namespace :admin do resources :subcategories end

  namespace :admin do resources :categories end

  namespace :admin do resources :mentors end

  namespace :admin do resources :mentees end

  namespace :admin do resources :home
	get "accounts"
  end

 	get "credentials/category"
	get "credentials/myprofile"
	get "credentials/studymat"
	get "credentials/career"
	get "credentials/contactus"
	get "credentials/question"
  devise_for :users, :path_names => { :sign_up => "register" } 

  
   devise_scope :user do 

get "myprofiles/edit"
get "myprofiles/update"
get "myprofiles/index"
  resources :credentials 
   resources :users
resources :myprofiles
  resources :login
  resources :questions
  resources :answers
   root :to => 'credentials#index'
end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
<<<<<<< HEAD
  validates :name, :presence => true
 # acts_as_rateable
=======
 validates :name, :presence => true
 
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
layout 'application'
prepend_before_filter :authenticate_user!
  # GET /answers
  # GET /answers.xml
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.xml
  def show
   # @answer = Answer.find(params[:id])
    @ques = Question.find(params[:id])
    @answerlist = Answer.where("question_id = ?", @ques.id )
    
    

    #respond_to do |format|
     # format.html # show.html.erb
    #  format.xml  { render :xml => @answer }
   # end
  end

  # GET /answers/new
  # GET /answers/new.xml
  def new
    @ques = Question.find(params[:id])
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.xml
  def create
    @answer = Answer.new(params[:answer])
    @answer.question_id = params[:q_id].to_i
    @answerlist = Answer.where("question_id = ?", @answer.question_id)   
    @question = Question.find(params[:q_id]) 
    @answer.user_id=current_user.id
   respond_to do |format|
    if @answer.save     
    format.html { render :action => "create"}

    else 
        puts '*******************'
        format.html { redirect_to :action => "new",:id => @answer.question_id }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
        
      end   
   end
  end

  # PUT /answers/1
  # PUT /answers/1.xml
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
       # format.html { redirect_to(@answer, :notice => 'Answer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.xml
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to(answers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<h1>Submit Answer</h1><br />

<%= form_for(Answer.new,:url=>{:action=>:create}) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3> Question : <%= @ques.name %> </h3>

  <div class="field">
   <h3> <%= f.label :Answer%></h3>
    <%= f.text_area :name, :rows => 10,:cols => 60 %>
  </div>
  <div class="actions">
<%=hidden_field_tag 'q_id',params[:id] %>
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/create.html.erb
<html>
<body >
<p id="notice"><%= notice %></p>
<<<<<<< HEAD
=======

>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d

<p>
  
<h2> <b>Question:</b> <%= @question.name %></h2>
<br /> <br />

</p>
<% @answerlist.each do |ans| %>
  <tr>
     <td> <h3><%= ans.name%> </h3></td>   
     <p>Posted <%= time_ago_in_words(ans.created_at) %> ago</p> 
<% end%>
</body>
</html>

app/views/answers/display.html.erb
<br/><br/><html>
<body bgcolor = "silver">
<p id="notice"><%= notice %></p>

<p>
  
<h2> <b>Question:</b> <%= @question.name %></h2>
<br /> <br />

</p>
<% @answerlist.each do |ans| %>
  <tr>
     <td> <h3><%= ans.name%> </h3></td>   
     <p>Posted <%= time_ago_in_words(ans.created_at) %> ago</p> 
<% end%>
</body>
</html>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>
<body bgcolor="Red"></body>
<table>
  <tr>
    <th>Name</th>
    <th>Question</th>   
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.name %></td>
    <td><%= answer.question_id %></td>

    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

app/views/answers/new.html.erb
<html>
<body>
<%= render 'form' %>

</body>
</html>

app/views/answers/show.html.erb
<br/><br/><html>
<body>
<p id="notice"><%= notice %></p>
 

<p>
  
<h2> <b>Question:</b> <%= @ques.name %></h2>
<br /> <br />
<%= link_to "Answer This Question" ,:controller => 'answers',:action =>'new',:id => @ques.id%>
</p>
<% @answerlist.each do |answer| %>
  <tr>
     <td> <h3><%= answer.name%> </h3></td>   
 <!-- RATINGS        <%= link_to "1    |2   |3    |4|"%> -->

<% end%>


</body>
</html>