config/routes.rb
MentorMentee::Application.routes.draw do

 

  resources :answers
  resources :questions do 
 get 'load_subcategories',:on => :collection

end 

  namespace :admin do resources :subcategories end

  namespace :admin do resources :categories end

  namespace :admin do resources :mentors end

  namespace :admin do resources :mentees end

  namespace :admin do resources :home
	get "accounts"
  end

 	get "credentials/category"
	get "credentials/myprofile"
	get "credentials/studymat"
	get "credentials/career"
	get "credentials/contactus"
	get "credentials/question"
  devise_for :users, :path_names => { :sign_up => "register" } 

  
   devise_scope :user do 

get "myprofiles/edit"
get "myprofiles/update"
get "myprofiles/index"
  resources :credentials 
   resources :users
resources :myprofiles
  resources :login
  resources :questions
  resources :answers
   root :to => 'credentials#index'
end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/category.rb
class Category < ActiveRecord::Base

has_many :subcategories

<<<<<<< HEAD
=======

>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d
has_many :subcategories, :dependent => :destroy
validates_presence_of :name
validates_uniqueness_of :name, :case_sensitive => false

<<<<<<< HEAD
end
=======
end 
>>>>>>> 31a48f4099fcbb35cb380bbc2504ca17d5c6e96d

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
layout 'admin/dashboard'
  # GET /admin/categories
  # GET /admin/categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
	flash[:notice] = 'Category was successfully created.'
       
        format.html { redirect_to([:admin,@category]) }
	 format.js
        format.xml  { render :xml => [:admin,@category], :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
	format.js
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to([:admin,@category], :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(admin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<table  class="stats" cellspacing="0">
<%= form_for([:admin,@category]) do |f| %>
 

 <tr><td> <div class="field"><br /><br />
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.label :Category %>
    &nbsp;&nbsp;<%= f.text_field :name %> <br/><br />
  </div>
  <div class="actions">
<%= f.submit %></td></tr>
  </div>
<% end %></table>

app/views/admin/categories/_formduplicate.html.erb
<%= form_for([:admin,Category.new], :remote=> true) do |f| %>
 

  <div class="field"><br /><br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.label :Category %>
    &nbsp;&nbsp;<%= f.text_field :name %> 
  </div><br/><br />
  <div class="actions">
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
 <%= stylesheet_link_tag 'saveedit',:media => "all" %>	
<img src="/images/editingcategory.gif" border="0"/><br/>

<%= render 'form' %><br/>



<ul id="css3menu" class="topmenu">
	
	<li class="topfirst"><%= link_to 'Back', admin_categories_path %> </li>
	
</ul></td>

<%= link_to image_tag("/images/back.gif", :border=>0), admin_categories_path %>   -->

app/views/admin/categories/index.html.erb
<img src="/images/Listingcategories.gif" border="0"/><br/>
<a href="#" onclick="Effect.toggle('form','blind');" ><img src="/images/newcategory.gif" border="0"/></a><br />
<div id="form" style="background-color:#CCCCCC; width: 550px; display:none;"><br />
<%=render :partial=>'formduplicate'%><br /><br />
</div>

<table id='cat' class="stats" cellspacing="0">
  <tr>
    <th><h3>Categories</h3></th>

  </tr>
<ul>
<% @categories.each do |admin_category| %>
  <tr>
   <td><%= link_to admin_category.name, :action=> 'show', :id => admin_category.id  %>
           <%= "(#{admin_category.subcategories.count})" -%></td>
</ul>
   


 <!--     <td><%= link_to 'Show',:action=> 'show', :id => admin_category.id %></td>
  <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
    <td><%= link_to 'Destroy',  :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<!--   <%= link_to 'New Category', new_admin_category_path %>   -->

app/views/admin/categories/new.html.erb
<h1>New category</h1><br/><br/>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
 <%= stylesheet_link_tag 'saveedit',:media => "all" %>	
<p id="notice"><%= notice %></p>
<table  class="stats" cellspacing="0">

 <th> <b><h1> 
  <%= @category.name %></h1></b></th>
<br/>


<tr>
<%@category.subcategories.each do |s|%>
  <td><%= s.name%></td></tr>
<%end%> </table
<br/>

<ul id="css3menu" class="topmenu">
	<li class="topfirst"><%= link_to 'Edit',  edit_admin_category_path(@category) %> </li>
	<li class="topmenu"><%= link_to 'Back', admin_categories_path %> </li>
	<li class="toplast"><%= link_to 'Destroy',  @admin_category, :confirm => 'Are you sure?', :method => :delete  %> </li>

</ul>